FROM node:22-alpine
RUN apk upgrade --no-cache
WORKDIR /app

COPY timoun-back/package*.json ./
RUN npm ci

COPY timoun-back/ .
RUN npm run build

ENV NODE_ENV=production
EXPOSE 1337
CMD ["npm", "run", "start"]